### ISSUE TITLE
Unable to show gif, if asset file is in another package

### ISSUE THREAD

**Issue by johnebere58** [RafaelBarbosatec/gif_view#1]
I keep getting an error message like this, when trying to load a gif asset from another package

E/flutter ( 6909): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Unable to load asset: 
assets/success.gif
E/flutter ( 6909): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)

**Comment by rafaelbarbosadrip** [comment]
I will adds the `package` param in `GifView.asset`

**Comment by johnebere58** [comment]
Greatl! thank you

**Comment by rafaelbarbosadrip** [comment]
Available in `0.1.1` version˜
