### ISSUE TITLE
frameRate not changing

### ISSUE THREAD

**Issue by SwiftyFlow** [RafaelBarbosatec/gif_view#13]
Hi I'm trying to let the user adjust the frame rate but it doesn't work... Got a slider for that:

Padding(
          padding: const EdgeInsets.only(top: 10.0, left: 10.0, right: 10.0, bottom: 2.0),
          child: Slider(
            inactiveColor: Colors.black38,
            activeColor: Colors.black,
            thumbColor: Colors.black,
            value: _currentGifDelayValue.toDouble(),
            max: 60,
            min: 0,
            divisions: 60,
            onChanged: (value) {
              setState(() {
                _currentGifDelayValue = value.toInt();
              });
            },
          ),
        ),

setState is there it reloads properly:

GifView.asset(
          globals.gifFile!.path,
          frameRate: _currentGifDelayValue,
),

but the speed/frameRate is the same...

Can you help? Or am I confusing what frameRate does?

**Comment by RafaelBarbosatec** [comment]
Hi @SwiftyFlow !
The Flutter always try recycling the widgets, Try adds the random Key in the GifView. It’s will work!

**Comment by SwiftyFlow** [comment]
Yep indeed I arrived to this point an hour ago hahaha and it worked already better. Also if anybody hits the problem, having a slider really doesn't help as it calls setState too often, I went for increment/decrement buttons instead and bang, job done. Thanks for the answer mate!
