### ISSUE TITLE
The 'play' code doesn't work when there is more than one gifview.

### ISSUE THREAD

**Issue by RubyKiss** [RafaelBarbosatec/gif_view#16]
![image](https://github.com/RafaelBarbosatec/gif_view/assets/19652699/75eedc88-70d8-4ac1-bde6-0172629813a2)
The 'play' code doesn't work when there is more than one gifview.

**Comment by RubyKiss** [comment]
in windows platform

**Comment by RafaelBarbosatec** [comment]
Solve in `0.4.3`. Please check the [example](https://github.com/RafaelBarbosatec/gif_view/blob/main/example/lib/main.dart).
