### ISSUE TITLE
Caching causes subsequent images to fail to load.

### ISSUE THREAD

**Issue by pharanbrush** [RafaelBarbosatec/gif_view#17]
https://github.com/RafaelBarbosatec/gif_view/blob/962d3ce8a360da49916888ee1178a9fc7ed8abe2/lib/gif_view.dart#L207C0-L215C11

The internal frame cache uses a map that makes keys out of known types, but does not cover all types.

For example, when you try to load gifs from files. (eg, using [FileImage](https://api.flutter.dev/flutter/painting/FileImage-class.html)), it always uses an empty String as the key and thinks everything that isn't a NetworkImage, AssetImage, or MemoryImage is the same image.

```dart
final gifImage = FileImage(File(file.path));

return Center(child: GifView(image: gifImage));
```
This will cause the GifView widget to retain the first image it loads because every FileImage is identified in the map as the same key of empty String.

**Comment by RafaelBarbosatec** [comment]
Fixed in `0.4.1` version.
