### ISSUE TITLE
onFinish, ImageRepeat.noRepeat not working

### ISSUE THREAD

**Issue by what2003** [RafaelBarbosatec/gif_view#2]
GifView.network(
            'https://gifs.eco.br/wp-content/uploads/2021/08/engracados-memes-gif-19.gif',
            height: 200,
            repeat: ImageRepeat.noRepeat,
            onFinish: () {
              logger.d('finishe````');
            },
          ),

from example, tried some function none of them working? 
if they do, this is a great package!

**Comment by RafaelBarbosatec** [comment]
Hi @what2003 !
The 'onFinish' works when you set 'loop' equals false.

**Comment by what2003** [comment]
Thank you and it works perfect now, in those gif packages this is the best one so far!
More introduction would be better, and maybe a progresser during loading. 
Keep up the good work!
