### ISSUE TITLE
Frame delay before starting gif

### ISSUE THREAD

**Issue by 1encore** [RafaelBarbosatec/gif_view#8]
There is a delay for about 6-7 seconds before the gif initialization.

Tested on Flutter v3.3.3
Simulator device iPhone 14 Pro

Flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5.1 21G83 darwin-x64, locale
    ru-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.72.2)`

**Comment by RafaelBarbosatec** [comment]
Hi @1encore !
I couldn't reproduce this problem. You could give us more Information? You tried load gif from assets or network?
